### ISSUE TITLE
Editorial pass pre FPWD

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/dapt#112]
## Check consistency of "is represented by" vs "is represented in TTML by"

We have a mix of:
* "[object] is represented [by|with]" and
* "[object] is represented in TTML [by|with]"

For editorial consistency, decide which one we want/need, and make sure we use the same choice everywhere.

**Comment by cconcolato** [comment]
Editorial bugs to fix or clarifications to make:
- [ ] In https://w3c.github.io/dapt/#intro-dubbing, the text "and considering reading speeds and shot changes." should be removed as there is no reading speeds and shot changes considerations in dubbing, it was initially text associated to "subtitling" and the word "subtitling" was removed but not the rest.
- [ ] Example 10 uses `begin="0"` and `begin="1.5s"`. For consistency, `0` should be `0s`
- [ ] The first note in https://w3c.github.io/dapt/#timing-properties should say "[End](https://w3c.github.io/dapt/#dfn-end) and [Begin](https://w3c.github.io/dapt/#dfn-begin) + [Duration](https://w3c.github.io/dapt/#dfn-duration)." (instead of Begin)
- [ ] In a script event, we should clarify that it is still possible to mark a specific word or words with a different language than the Text without having to create a new Script Event
- [ ] In https://w3c.github.io/dapt/#Document%20Encoding, to avoid doubt in the actual quote, we should put the corresponding unicode code-point
- [ ] The profile designator used in the examples (https://w3c.github.io/dapt/#example-1, `http://www.w3.org/ns/ttml/profile/dapt`) does not match the one defined in https://w3c.github.io/dapt/#profile-designator (`http://www.w3.org/ns/dapt/profile/content`).
