### ISSUE TITLE
Consider identifying DAPT metadata from other metadata

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#147]
The spec currently says:
> All `<ttm:agent>` elements SHOULD be contained in the first `<metadata>` element in the `<head>` element.
> NOTE: There can be multiple `<metadata>` elements in the `<head>` element, for example to include [proprietary metadata](https://w3c.github.io/dapt/#proprietary-metadata) but the above recommends that only one is used to define the characters.

The "should" is meant to permit mixing different types of metadata, from different applications. That is fine. But the problem is that is not easy to spot which metadata to ignore and which metadata to process. I wonder if we shouldn't say: if a metadata has an attribute set (e.g. daptm:metadataType='character'), then it is shall contain only the definition of DAPT characters.

**Comment by nigelmegitt** [comment]
I don't think we really know enough about how people might use this right now. I'm not even sure we have enough motivation for the current SHOULD statement.

Instead I would propose to relax the constraint, so that an xpath of `/tt/head/metadata/ttm:agent` can be used to select all the `<ttm:agent>` elements regardless of which `<metadata>` element they are in. If there's some application-specific constraint where certain `<metadata>` elements have different significance than other ones, then we need to know the use case for that and whether it is appropriate for standardisation or can be specified in a more local or specific environment.

For example, I could imagine that someone creating scripts for several episodes in a series might have a "series-level" metadata element that they maintain, with tooling to update it across the documents relating to all the episodes, and an additional episode level metadata element containing the metadata unique to each episode. That approach could make managing character and actor metadata easier.

**Comment by cconcolato** [comment]
My goal is to try and simplify implementations. I prefer being strict in a v1 and relaxing rules in a v2 when use cases come.

**Comment by nigelmegitt** [comment]
Understood, but I worry that we are optimizing too soon for implementation simplicity. Do we have any data points from implementers about the additional complexity of having `<ttm:agent>`s potentially distributed amongst multiple `/tt/head/metadata` elements?
