### ISSUE TITLE
Required metadata field for earliest SMPTE time code to allow conversion between DAPT and ESEF

### ISSUE THREAD

**Issue by ewanrsmith** [w3c/dapt#232]
Descriptions in ESEF files are timed via SMPTE timecodes so to convert to and from DAPT a key time code must be included in the metadata from which the timecodes of all other descriptions can be extrapolated. An existing EBUTT metadata field - documentStartOfProgramme - would be an obvious candidate for this but this value isn't typically recorded in an ESEF file. 

@nigelmegitt  proposes a new DAPT metadata value - equivalent to the ESEF format's first_content_tc - that all other relative values can be synchronised against.

**Comment by nigelmegitt** [comment]
As discussed with @ewanrsmith here's a diagram representing the different timelines, showing where some alignment point is likely needed:

![image](https://github.com/w3c/dapt/assets/4988915/b74f3438-ce22-456b-a7f1-4f9f7da985c4)

For audio description workflows that need to generate a WAV file to be played out co-synchronously with the programme media, some process, often known as "compilation" is needed to take the source DAPT and any referenced audio recordings and generate the audio output file. In some workflows a "handle" is prepended to the WAV file for use as a kind of pre-roll.

Two key pieces of data are needed for the compilation process, both of which are _external_ to the DAPT document itself:
1. The begin time, which may be the start of programme content or be the earlier by the duration of the handle
2. The end time

Depending on how the DAPT was authored, the begin time, referenced to the DAPT document's media timeline, could be earlier than (less than) zero. In some cases the begin time is expressed in SMPTE timecode rather than media time.

In order to support compilation processes that express the begin time in SMPTE timecode, some alignment between the DAPT document's media timeline and the relevant SMPTE timeline is needed.

The proposal is to add optional document-level metadata that defines the SMPTE timecode that corresponds to media time zero in the DAPT document. For this metadata to be interpreted correctly, a frame rate, frame rate multiplier and dropMode are likely needed.

An alternative solution to this problem would be to permit time expressions to use SMPTE timecode: I'm reluctant to go down that route because:
1. The output audio must be a single continuous and contiguous resource, so it is not useful to allow time expressions that support potential discontinuities.
2. Implementation experience e.g. in the domain of subtitles and captions, has shown that conversion of SMPTE timecode using non-integer frame rates is a significant source of interoperability problems in implementations.

Note that as per the diagram, in some cases the `ebuttm:documentStartOfProgramme` metadata from the EBU's [Tech3390 EBU-TT, Part M Metadata Definitions](https://tech.ebu.ch/publications/tech3390) may be present, however it does _not_ represent the same thing, and forcing it to do so would constitute a misuse.

**Comment by nigelmegitt** [comment]
I've opened a pull request to add a feature to support this, #240, if you'd like to take a look at it @ewanrsmith .
