### ISSUE TITLE
[ED issue] Do we need one or two profiles?

### ISSUE THREAD

**Issue by cconcolato** [w3c/dapt#46]
Even if the specification makes sense in aggregating the use cases of Dubbing and Audio Description, it is likely that some implementations that do Dubbing only will not support audio and animation features. Should we define 2 profiles: one with audio/animation support and one without?

**Comment by nigelmegitt** [comment]
Discussed in TTWG meeting 2022-09-16 - views both in favour of, and against, having two profiles were expressed. Question remains open.

There may be a way to have two profiles without being "heavy" about it, by defining different conformance classes of processor, one of which supports more features than the other. They'd still effectively be two profiles, in practice.

**Comment by nigelmegitt** [comment]
As a result of #104 and #103 I have realised that we are effectively defining _at least_ a Content Profile and a Processor Profile, since the mapping of conformance terms to the TTML2 values of the `ttp:feature@value` attribute in the profile definition is different depending which of those it is:

* For a Processor Profile, no semantic is defined in TTML2 for "prohibited"
* No value is defined in TTML2 that is equivalent to the DAPT "permitted" value, which means "optional in content, required in processor".

CC @skynavga who may be interested.

**Comment by cconcolato** [comment]
We don't think there is a need to define more profiles, e.g. one per workflow type. So we're closing this issue but we might still want have restrictions per workflow type (see #75)
